export const listAttendanceRow = [
  {
    id: 1,
    studentId: "DH52006097",
    studentName: "Văn Bảo Tâm",
    class: "D20_TH09",
    times_1: "X",
    times_2: "O",
    times_3: "X",
    times_4: "X",
    times_5: "O",
    times_6: "X",
    times_7: "X",
    times_8: "O",
    times_9: "X",
    times_10: "X",
    times_11: "O",
    times_12: "X",
    times_13: "X",
    times_14: "O",
    times_15: "X",
  },
  {
    id: 2,
    studentId: "DH52006098",
    studentName: "Văn Bảo Tâm",
    class: "D20_TH10",
    times_1: "X",
    times_2: "O",
    times_3: "X",
    times_4: "O",
    times_5: "O",
    times_6: "X",
    times_7: "X",
    times_8: "O",
    times_9: "X",
    times_10: "X",
    times_11: "O",
    times_12: "X",
    times_13: "X",
    times_14: "O",
    times_15: "X",
  },
  {
    id: 3,
    studentId: "DH52006099",
    studentName: "Văn Bảo Tâm",
    class: "D20_TH08",
    times_1: "X",
    times_2: "O",
    times_3: "X",
    times_4: "X",
    times_5: "O",
    times_6: "X",
    times_7: "X",
    times_8: "O",
    times_9: "X",
    times_10: "X",
    times_11: "O",
    times_12: "X",
    times_13: "X",
    times_14: "O",
    times_15: "X",
  },
  {
    id: 4,
    studentId: "DH52006100",
    studentName: "Văn Bảo Tâm",
    class: "D20_TH09",
    times_1: "X",
    times_2: "O",
    times_3: "X",
    times_4: "O",
    times_5: "O",
    times_6: "X",
    times_7: "X",
    times_8: "O",
    times_9: "X",
    times_10: "X",
    times_11: "O",
    times_12: "X",
    times_13: "X",
    times_14: "O",
    times_15: "X",
  },
];
export const attendanceFaceRow = [
  {
    id: 1,
    studentId: "DH52006097",
    studentName: "Văn Bảo Tâm",
    class: "D20_TH09",
    isAttendanced: "YES",
  },
  {
    id: 2,
    studentId: "DH52006097",
    studentName: "Văn Bảo Tâm",
    class: "D20_TH09",
    isAttendanced: "YES",
  },
  {
    id: 3,
    studentId: "DH52006097",
    studentName: "Văn Bảo Tâm",
    class: "D20_TH09",
    isAttendanced: "YES",
  },
  {
    id: 4,
    studentId: "DH52006097",
    studentName: "Văn Bảo Tâm",
    class: "D20_TH09",
    isAttendanced: "YES",
  },
];

export const CourseAttendanceRow = [
  {
    id: 1,
    courseName: "Tin học cơ bản",
    startDate: "15/04/2024",
    endDate: "19/05/2024",
    times_1: "X",
    times_2: "O",
    times_3: "X",
    times_4: "X",
    times_5: "O",
    times_6: "X",
    times_7: "X",
    times_8: "O",
    times_9: "X",
    times_10: "X",
    times_11: "O",
    times_12: "X",
    times_13: "X",
    times_14: "O",
    times_15: "X",
  },
  {
    id: 2,
    courseName: "Tin học cơ bản",
    startDate: "16/04/2024",
    endDate: "20/05/2024",
    times_1: "X",
    times_2: "O",
    times_3: "X",
    times_4: "O",
    times_5: "O",
    times_6: "X",
    times_7: "X",
    times_8: "O",
    times_9: "X",
    times_10: "X",
    times_11: "O",
    times_12: "X",
    times_13: "X",
    times_14: "O",
    times_15: "X",
  },
  {
    id: 3,
    courseName: "Word",
    startDate: "16/04/2024",
    endDate: "20/05/2024",
    times_1: "X",
    times_2: "O",
    times_3: "X",
    times_4: "X",
    times_5: "O",
    times_6: "X",
    times_7: "X",
    times_8: "O",
    times_9: "X",
    times_10: "X",
    times_11: "O",
    times_12: "X",
    times_13: "X",
    times_14: "O",
    times_15: "X",
  },
  {
    id: 4,
    courseName: "Excel",
    startDate: "16/04/2024",
    endDate: "20/05/2024",
    times_1: "X",
    times_2: "O",
    times_3: "X",
    times_4: "O",
    times_5: "O",
    times_6: "X",
    times_7: "X",
    times_8: "O",
    times_9: "X",
    times_10: "X",
    times_11: "O",
    times_12: "X",
    times_13: "X",
    times_14: "O",
    times_15: "X",
  },
];
